#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Mar 11 01:59:20 MST 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 9650b317814841dfb2bff3d6789a6a2e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot DoubleSevenSegmentTest_behav xil_defaultlib.DoubleSevenSegmentTest xil_defaultlib.glbl -log elaborate.log"
xelab -wto 9650b317814841dfb2bff3d6789a6a2e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot DoubleSevenSegmentTest_behav xil_defaultlib.DoubleSevenSegmentTest xil_defaultlib.glbl -log elaborate.log

